### PR TITLE
Fix broken count

### LINKED ISSUE #49: Calling .count throws error
I suppose I'd expect Model.count to return nil, if not 0. However, with Rails 4.0.0 and up it brings ActiveRecord to its knees.

Minimal demonstrative project [here](https://github.com/christhekeele/nulldb-count-error). Comes with whatever `rails g scaffold Foo bar:string` produces, a pre-migrated sqlite db, a single test that asserts `Foo.count`, and `pry` required in `spec_helper.rb` for your error-plumbing convenience.

Reproducing it should be as easy as

``` sh
git clone git@github.com:christhekeele/nulldb-count-error.git asdf
cd asdf
bundle install
bundle exec rspec .
#=> TypeError: no implicit conversion from nil to integer
```

This is not (as I initially suspected) anyone trying to cast a `nil` to a valid return for `count`, but from

``` ruby
# /usr/local/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activerecord-4.0.2/lib/active_record/relation/calculations.rb:265
...
  def execute_simple_calculation(operation, column_name, distinct)
    ...
      column = result.column_types.fetch(column_alias) do #265
        column_for(column_name)
      end
```

...where `result` is a `ActiveRecord::ConnectionAdapters::NullDBAdapter::EmptyResult`,

`column_types` evaluates to `[]` from `nulldb/lib/active_record/connection_adapters/nulldb_adapter.rb:103`,

and `column_alias` is a `nil` from ActiveSupport's `NilClass.try(*args); nil; end`.

### PR DESCRIPTION
**Pull request by mach-kernel**
Resolves #49.

It appears that the ActiveRecord API has changed or maybe was interpreted incorrectly (?) causing this error. [I went on a small adventure](https://github.com/davidcelis/api-pagination/pull/95#issuecomment-397853842) trying to figure this one out and came to the conclusion that all of the other piping is fine and that a small tweak to the API of the nulldb `EmptyResult` object gives us a solution.

ActiveRecord uses the type metadata in this context, in `active_record/relations/calculations.rb` inside `#execute_simple_calculation`: 

```ruby
type   = result.column_types.fetch(column_alias) do
  type_for(column_name)
end
```

Well, it looks like we need to see what the `Result` API should implement. [What better place than the spec?](https://github.com/rails/rails/blob/15ef55efb591e5379486ccf53dd3e13f416564f6/activerecord/test/cases/result_test.rb)

```
    test "cast_values uses identity type for unknown types" do
      values = [["1.1", "2.2"], ["3.3", "4.4"]]
      columns = ["col1", "col2"]
      types = { "col1" => Type::Integer.new }
      result = Result.new(columns, values, types)

      assert_equal [[1, "2.2"], [3, "4.4"]], result.cast_values
    end
```

Cool. We need a Hash of column names to reified `ActiveRecord::Type` objects! Problem solved. I implemented this interface, but there was another issue:

```ruby
[1] pry(#<ActiveRecord::ConnectionAdapters::NullDBAdapter>)> ActiveRecord::Type.lookup(:primary_key)                                                                                       
ArgumentError: Unknown type :primary_key
from /home/mach/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.2.0/lib/active_model/type/registry.rb:22:in `lookup'                                                          
```

We also have to register a `:primary_key` type with the `ActiveRecord::Type` registry, as this is a fairly common configuration that is exposed via `schema.rb`, so this functionality was also added to the project. 

I added a spec to check that `count` works, which previously did not exist and would fail without these changes as below: 

```
Failures:                                                                                                                                                                                   
                                                                                                                                                                                            
  1) NullDB should handle count queries                                                                                                                                                     
     Failure/Error: expect(Employee.count).to eql(0)                                                                                                                                        
                                                                                                                                                                                            
     TypeError:                                                                                                                                                                             
       no implicit conversion of String into Integer                                                                                                                                        
     # ./spec/nulldb_spec.rb:292:in `block (2 levels) in <top (required)>'                                                                                                                  
                                                                                                                                                                                            
Finished in 0.05611 seconds (files took 0.45248 seconds to load)                                                                                                                            
38 examples, 1 failure                                                                                                                                                                      
                                                                                                                                                                                            
Failed examples:                                                                                                                                                                            
                                                                                                                                                                                            
rspec ./spec/nulldb_spec.rb:291 # NullDB should handle count queries

Coverage report generated for RSpec to /home/mach/Workspace/nulldb/coverage. 250 / 311 LOC (80.39%) covered.                                                                               
```

There is also a spec around the type registry change. I hope that this solves a lot of workarounds!

### CODE REVIEW

**Comment by mach-kernel** [comment]
Looks like I broke everything < ActiveRecord 5.0. I think I found the [API equivalent](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/type/type_map.rb) for 4.2x. 

I didn't look yet how far back that convention goes, however we could also just not register the type and add a note in the README. I await your feedback.

**Comment by mnoack** [comment]
@mach-kernel Technically nulldb still passes specs with rails 2, but I don't expect people to support rails 2 or even 3, but I think 4 should be supported (but I'm open for discussion).

Basically try to get the specs passing, but I'm happy to drop rails 2/3 support if needed (those needing legacy support can stick to old gem versions)

**Comment by mach-kernel** [comment]
@mnoack I fixed it!

**Comment by mach-kernel** [comment]
@mnoack :wave:, let me know if there's anything left to do for getting this out 😸

File: lib/nulldb/core.rb [hunk 1]
```diff
@@ -3,6 +3,9 @@
 require 'active_record/connection_adapters/nulldb_adapter'
 
 module NullDB
+  LEGACY_ACTIVERECORD = 
+    (ActiveRecord::VERSION::MAJOR < 5) && (ActiveRecord::VERSION::MINOR < 2)
```
Comment (mnoack) [inline lib/nulldb/core.rb]: Would this mean ActiveRecord 4.1 is legacy, but 3.2 is not (because it's minor is not less than 2)

**Comment by mnoack** [comment]
@mach-kernel - One comment, but otherwise I'm quite happy. It passes the tests and you've added a new test which is all good.

**Comment by mach-kernel** [comment]
@mnoack looks like it breaks with `master` ActiveRecord. I can investigate this if needed, but I don't think it would be a good idea to build against new APIs or even API changes until it is officially decided that they wish to release.

**Comment by mnoack** [comment]
@mach-kernel - Sorry finally got around to this. Yes master doesn't matter (I should work out how to exclude that test from the build). It's just so we can ensure we stay compatible with the latest rails as there are changes.

I've released a gem version with your changes and some other recent PRs since the last release.
